### ISSUE TITLE
雷达与IMU时间同步应该怎么做？

### ISSUE THREAD

**Issue by YJZLuckyBoy** [YushengWHU/HS-LiDAR-dataset#1]
您好，感谢您分享的数据集，请问您的雷达和IMU时间同步是怎么做的？方便告知一些方式吗？此外最大上传20G的限制，感觉可以通过分卷压缩方式依次上传上来，期待您的回复！

**Comment by YushengWHU** [comment]
雷达和IMU时间同步最简单的就是ptp即可做，这个也是最方便的，我试试分卷上传看看，谢谢

**Comment by YJZLuckyBoy** [comment]
感谢回复，因为之前没有做过ptp同步，最近看资料有几个疑问，希望您能帮忙解答一下：1. 我现在lidar通过网口连接pc，imu是通过usb口连接pc，是不是现在只需在pc端设置好ptp就可以完成同步了，相当于ptp模拟了一个时钟源，同时给到lidar和imu？2. 还有一个问题就是我看到ouster官网给出了ptp同步方案，而且pc端设置好ptp后，雷达也要配置成1588模式，而禾赛和速腾没有看到相关的ptp同步教程，那么现在是不是我只需要在pc端设置好ptp，然后使用的lidar驱动和IMU驱动都改成ros::Time::now即可完成ptp时间同步？还请解惑，谢谢

**Comment by YushengWHU** [comment]
1. 主要主机支持PTP，（可以网上查一下怎么看是否支持），然后网线插入lidar，usb插入IMU，ifconfig查看网卡号（比如eno1），使用`sudo ptpd -M -i eno1`即可ptp同步好雷达（ros时）。imu的话你得在驱动里改成ros::time::now
2. 禾赛和速腾也跟上面方法一样，包括livox

**Comment by smxshuimuxiao** [comment]
> 1. 主要主机支持PTP，（可以网上查一下怎么看是否支持），然后网线插入lidar，usb插入IMU，ifconfig查看网卡号（比如eno1），使用`sudo ptpd -M -i eno1`即可ptp同步好雷达（ros时）。imu的话你得在驱动里改成ros::time::now
> 2. 禾赛和速腾也跟上面方法一样，包括livox

感谢解答，我会按照您给的方法试一下

**Comment by YJZLuckyBoy** [comment]
> 1. 主要主机支持PTP，（可以网上查一下怎么看是否支持），然后网线插入lidar，usb插入IMU，ifconfig查看网卡号（比如eno1），使用`sudo ptpd -M -i eno1`即可ptp同步好雷达（ros时）。imu的话你得在驱动里改成ros::time::now
> 2. 禾赛和速腾也跟上面方法一样，包括livox

感谢解惑，我按照您的方法试一下，非常感谢！
